Hw 2 count det
RomanMatiiv/made-cpp-2020-hw pull request #2
Opened 2020-09-28 00:53 UTC by RomanMatiiv

2020-10-01 11:37 UTC, SweetWeakness requested changes

2020-10-01 11:37 UTC, SweetWeakness commented on count_det/src/main.s
> +        ldr r4, [r0, #4 * 8]
нужно сохранять значение регистров r4+ до вызова

2020-10-04 20:10 UTC, RomanMatiiv commented on count_det/src/main.s
> +        ldr r4, [r0, #4 * 8]
исправил, добавил push {r4}   pop {r4}

2020-10-05 13:11 UTC, SweetWeakness approved these changes

2020-10-05 13:11 UTC, merged