Proj 1 vector operations
RomanMatiiv/made-cpp-2020-hw pull request #3
Opened 2020-10-06 19:54 UTC by RomanMatiiv

2020-10-17 23:58 UTC, xterrafunny requested changes

2020-10-17 23:58 UTC, xterrafunny commented on vector_operations/src/vector_ops.h
> +{
Фигурная скобка должна быть на предыдущей строке

2020-10-17 23:58 UTC, xterrafunny commented on vector_operations/src/vector_ops.h
> +    vector<double> tmp (a.size());
Не нужен пробел перед списком аргументов

2020-10-17 23:58 UTC, xterrafunny commented on vector_operations/src/vector_ops.h
> +        scalar_product+= (a[i] * b[i]);
Бинарные операторы отделяются пробелами с обеих сторон

2020-10-17 23:58 UTC, xterrafunny commented on vector_operations/src/vector_ops.h
> +    vector<double> tmp (a.size());
Отступы в 2 пробела

2020-10-17 23:58 UTC, xterrafunny commented on vector_operations/src/vector_ops.h
> +//}
Где?

2020-10-31 22:59 UTC, SweetWeakness commented
Давно от вас новостей не было. Мерджить не можем ваш проект, так как мердж-конфликты. Ставим вам на портале частичный балл, но вам обязательно нужно самостоятельно вмерджить проект.

2020-10-31 22:59 UTC, SweetWeakness approved these changes

2020-11-03 03:07 UTC, merged